plugins {
    id 'kotlin'
}

java {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Kotlin.coroutines}"
    implementation "javax.inject:javax.inject:${Jvm.inject}"
    implementation "com.squareup.retrofit2:retrofit:${Network.retrofit}"
}
